
const dbIntegrales = [
  // --- 1-20: POTENCIAS Y POLINOMIOS ---
  { q: "\\int x^3 \\, dx", a: ["\\frac{x^4}{4}+C", "3x^2+C", "x^4+C", "\\frac{x^3}{3}+C"], c: "\\frac{x^4}{4}+C", h: "Suma 1 al exponente y divide por el nuevo exponente." },
  { q: "\\int x^6 \\, dx", a: ["\\frac{x^7}{7}+C", "6x^5+C", "x^7+C", "7x^7+C"], c: "\\frac{x^7}{7}+C", h: "Aplica la regla de la potencia: (x^{n+1})/(n+1)." },
  { q: "\\int 4x^3 \\, dx", a: ["x^4+C", "12x^2+C", "4x^4+C", "\\frac{4x^3}{3}+C"], c: "x^4+C", h: "El 4 se cancela con el denominador 4 de la integración." },
  { q: "\\int (x^2 + x) \\, dx", a: ["\\frac{x^3}{3}+\\frac{x^2}{2}+C", "x^3+x^2+C", "2x+1+C", "\\frac{x^3+x^2}{2}+C"], c: "\\frac{x^3}{3}+\\frac{x^2}{2}+C", h: "Integra cada término por separado." },
  { q: "\\int 10x^9 \\, dx", a: ["x^{10}+C", "90x^8+C", "10x^{10}+C", "x^9+C"], c: "x^{10}+C", h: "Integral directa de una potencia con coeficiente." },
  { q: "\\int \\sqrt{x} \\, dx", a: ["\\frac{2}{3}x^{3/2}+C", "\\frac{3}{2}x^{3/2}+C", "x^{1/2}", "\\frac{1}{2\\sqrt{x}}"], c: "\\frac{2}{3}x^{3/2}+C", h: "Raíz de x es x^{1/2}. Suma 1 al exponente." },
  { q: "\\int x^{1/3} \\, dx", a: ["\\frac{3}{4}x^{4/3}+C", "\\frac{4}{3}x^{4/3}+C", "x^{4/3}+C", "\\frac{3}{4}x^{3/4}+C"], c: "\\frac{3}{4}x^{4/3}+C", h: "1/3 + 1 = 4/3. Divide por 4/3 (o multiplica por 3/4)." },
  { q: "\\int (3x^2 - 2x + 5) \\, dx", a: ["x^3-x^2+5x+C", "3x^3-2x^2+5x", "6x-2+C", "x^3-2x+5"], c: "x^3-x^2+5x+C", h: "Integra término a término." },
  { q: "\\int \\frac{1}{x^3} \\, dx", a: ["-\\frac{1}{2x^2}+C", "\\ln|x^3|+C", "\\frac{-3}{x^4}+C", "\\frac{1}{2x^2}+C"], c: "-\\frac{1}{2x^2}+C", h: "Súbelo como x^{-3} antes de integrar." },
  { q: "\\int \\frac{5}{x^6} \\, dx", a: ["-\\frac{1}{x^5}+C", "-x^{-5}+C", "5\\ln|x^6|", "\\frac{-5}{7x^7}+C"], c: "-\\frac{1}{x^5}+C", h: "5 * (x^{-5}/-5) simplifica el 5." },
  { q: "\\int 7 \\, dx", a: ["7x+C", "7+C", "0", "x^7+C"], c: "7x+C", h: "La integral de una constante k es kx." },
  { q: "\\int (x-1)(x+1) \\, dx", a: ["\\frac{x^3}{3}-x+C", "x^2-1+C", "\\frac{x^3}{3}+x+C", "2x+C"], c: "\\frac{x^3}{3}-x+C", h: "Primero multiplica: (x^2 - 1)." },
  { q: "\\int \\frac{x+1}{\\sqrt{x}} \\, dx", a: ["\\frac{2}{3}x^{3/2}+2x^{1/2}+C", "x^{3/2}+x^{1/2}+C", "\\sqrt{x}+C", "2\\sqrt{x}+C"], c: "\\frac{2}{3}x^{3/2}+2x^{1/2}+C", h: "Divide cada término por x^{1/2}." },
  { q: "\\int (8x^7 - 6x^5) \\, dx", a: ["x^8-x^6+C", "8x^8-6x^6+C", "56x^6-30x^4+C", "\\frac{x^8}{8}+C"], c: "x^8-x^6+C", h: "Los coeficientes se cancelan con los nuevos exponentes." },
  { q: "\\int \\sqrt[3]{x^2} \\, dx", a: ["\\frac{3}{5}x^{5/3}+C", "\\frac{5}{3}x^{5/3}+C", "x^{5/3}+C", "\\frac{3}{5}x^{2/3}+C"], c: "\\frac{3}{5}x^{5/3}+C", h: "x^{2/3} integrado es x^{5/3}/(5/3)." },
  { q: "\\int \\frac{1}{x^2} \\, dx", a: ["-\\frac{1}{x}+C", "\\frac{1}{x}+C", "\\ln|x^2|", "-2x^{-3}+C"], c: "-\\frac{1}{x}+C", h: "Recuerda que la integral de x^{-2} es -x^{-1}." },
  { q: "\\int 4 \\sqrt{x^3} \\, dx", a: ["\\frac{8}{5}x^{5/2}+C", "\\frac{5}{8}x^{5/2}+C", "x^{5/2}+C", "6\\sqrt{x}"], c: "\\frac{8}{5}x^{5/2}+C", h: "4 * x^{3/2} integrado es 4 * (2/5)x^{5/2}." },
  { q: "\\int (1 - x)^2 \\, dx", a: ["x-x^2+\\frac{x^3}{3}+C", "\\frac{(1-x)^3}{3}+C", "1-2x+x^2+C", "-2(1-x)"], c: "x-x^2+\\frac{x^3}{3}+C", h: "Desarrolla el cuadrado: 1 - 2x + x^2." },
  { q: "\\int 2x(x^2+1) \\, dx", a: ["\\frac{x^4}{2}+x^2+C", "x^4+x^2+C", "2x^3+2x+C", "\\frac{x^4}{2}+C"], c: "\\frac{x^4}{2}+x^2+C", h: "Distribuye: 2x^3 + 2x." },
  { q: "\\int \\frac{2}{\\sqrt[5]{x}} \\, dx", a: ["\\frac{5}{2}x^{4/5}+C", "\\frac{2}{5}x^{4/5}+C", "x^{4/5}+C", "10x^{4/5}+C"], c: "\\frac{5}{2}x^{4/5}+C", h: "2 * x^{-1/5} integrado es 2 * (5/4)x^{4/5}." },

  // --- 21-40: TRIGONOMÉTRICAS ---
  { q: "\\int \\sin(x) \\, dx", a: ["-\\cos(x)+C", "\\cos(x)+C", "\\sin(x)+C", "-\\sin(x)+C"], c: "-\\cos(x)+C", h: "La integral del seno es el coseno negativo." },
  { q: "\\int \\cos(x) \\, dx", a: ["\\sin(x)+C", "-\\sin(x)+C", "\\cos(x)+C", "0"], c: "\\sin(x)+C", h: "La integral del coseno es el seno positivo." },
  { q: "\\int \\sec^2(x) \\, dx", a: ["\\tan(x)+C", "-\\tan(x)+C", "\\sec(x)+C", "\\cos(x)+C"], c: "\\tan(x)+C", h: "Integral inmediata: tan'(x) = sec²(x)." },
  { q: "\\int \\csc^2(x) \\, dx", a: ["-\\cot(x)+C", "\\cot(x)+C", "\\tan(x)", "-\\sec(x)"], c: "-\\cot(x)+C", h: "La integral de csc²(x) es -cot(x)." },
  { q: "\\int \\sec(x)\\tan(x) \\, dx", a: ["\\sec(x)+C", "\\tan(x)+C", "\\cos(x)", "\\csc(x)"], c: "\\sec(x)+C", h: "La derivada de la secante es sec(x)tan(x)." },
  { q: "\\int \\csc(x)\\cot(x) \\, dx", a: ["-\\csc(x)+C", "\\csc(x)+C", "-\\cot(x)+C", "\\tan(x)"], c: "-\\csc(x)+C", h: "La integral de csc(x)cot(x) es -csc(x)." },
  { q: "\\int \\sin(3x) \\, dx", a: ["-\\frac{1}{3}\\cos(3x)+C", "\\frac{1}{3}\\cos(3x)+C", "-3\\cos(3x)+C", "\\cos(3x)+C"], c: "-\\frac{1}{3}\\cos(3x)+C", h: "Usa sustitución u=3x, du=3dx." },
  { q: "\\int \\cos(4x) \\, dx", a: ["\\frac{1}{4}\\sin(4x)+C", "4\\sin(4x)+C", "-\\sin(4x)+C", "\\frac{1}{4}\\cos(4x)"], c: "\\frac{1}{4}\\sin(4x)+C", h: "Integral de cos(ax) es (1/a)sin(ax)." },
  { q: "\\int \\sec^2(2x) \\, dx", a: ["\\frac{1}{2}\\tan(2x)+C", "2\\tan(2x)+C", "\\tan(2x)+C", "\\frac{1}{2}\\sec(2x)"], c: "\\frac{1}{2}\\tan(2x)+C", h: "No olvides el factor 1/a de la sustitución u=2x." },
  { q: "\\int \\sin(x/2) \\, dx", a: ["-2\\cos(x/2)+C", "-\\frac{1}{2}\\cos(x/2)+C", "2\\cos(x/2)+C", "\\cos(x/2)+C"], c: "-2\\cos(x/2)+C", h: "Dividir por 1/2 es igual a multiplicar por 2." },
  { q: "\\int 5\\cos(x) \\, dx", a: ["5\\sin(x)+C", "-5\\sin(x)+C", "5\\cos(x)+C", "\\sin(5x)+C"], c: "5\\sin(x)+C", h: "La constante sale de la integral." },
  { q: "\\int (\\sin x + \\cos x) \\, dx", a: ["\\sin x - \\cos x + C", "\\cos x + \\sin x + C", "-\\cos x + \\sin x + C", "0+C"], c: "-\\cos x + \\sin x + C", h: "Integra cada función trigonométrica por separado." },
  { q: "\\int \\frac{1}{\\cos^2 x} \\, dx", a: ["\\tan x + C", "\\sec x + C", "\\cos x + C", "\\ln|\cos x|"], c: "\\tan x + C", h: "Recuerda que 1/cos²(x) es sec²(x)." },
  { q: "\\int \\frac{1}{\\sin^2 x} \\, dx", a: ["-\\cot x + C", "\\cot x + C", "\\csc x + C", "\\tan x"], c: "-\\cot x + C", h: "Recuerda que 1/sin²(x) es csc²(x)." },
  { q: "\\int \\cos(x+1) \\, dx", a: ["\\sin(x+1)+C", "-\\sin(x+1)+C", "\\cos(x+1)+C", "x\\cos x"], c: "\\sin(x+1)+C", h: "La derivada de x+1 es 1, así que es una integral simple." },
  { q: "\\int \\sin(\\pi x) \\, dx", a: ["-\\frac{1}{\\pi}\\cos(\\pi x)+C", "\\pi\\cos(\\pi x)+C", "\\cos(\\pi x)+C", "-\\cos(x)"], c: "-\\frac{1}{\\pi}\\cos(\\pi x)+C", h: "La constante interna es π." },
  { q: "\\int (2 - \\sin x) \\, dx", a: ["2x + \\cos x + C", "2x - \\cos x + C", "- \\cos x + C", "2 + \\cos x"], c: "2x + \\cos x + C", h: "La integral de -sin(x) es +cos(x)." },
  { q: "\\int \\sec^2(x/3) \\, dx", a: ["3\\tan(x/3)+C", "\\frac{1}{3}\\tan(x/3)+C", "\\tan(x/3)+C", "3\\sec(x/3)"], c: "3\\tan(x/3)+C", h: "Dividir por 1/3 equivale a multiplicar por 3." },
  { q: "\\int 4\\sin(4x) \\, dx", a: ["-\\cos(4x)+C", "-16\\cos(4x)+C", "\\cos(4x)+C", "-\\sin(4x)+C"], c: "-\\cos(4x)+C", h: "El 4 de afuera se cancela con el 1/4 de la sustitución." },
  { q: "\\int \\cos(x/4) \\, dx", a: ["4\\sin(x/4)+C", "\\frac{1}{4}\\sin(x/4)+C", "\\sin(x/4)+C", "-4\\sin(x/4)"], c: "4\\sin(x/4)+C", h: "Multiplica por el recíproco de 1/4." },

  // --- 41-60: EXPONENCIALES Y LOGARÍTMICAS ---
  { q: "\\int e^x \\, dx", a: ["e^x+C", "xe^x", "\\ln(e)", "e^{x+1}"], c: "e^x+C", h: "La función exponencial es la única que no cambia." },
  { q: "\\int e^{2x} \\, dx", a: ["\\frac{1}{2}e^{2x}+C", "2e^{2x}+C", "e^{2x}+C", "e^x"], c: "\\frac{1}{2}e^{2x}+C", h: "Integral de e^{ax} es (1/a)e^{ax}." },
  { q: "\\int e^{-x} \\, dx", a: ["-e^{-x}+C", "e^{-x}+C", "e^x+C", "-x e^{-x}"], c: "-e^{-x}+C", h: "El signo negativo baja al integrar." },
  { q: "\\int 5e^{5x} \\, dx", a: ["e^{5x}+C", "25e^{5x}+C", "5e^x+C", "e^x"], c: "e^{5x}+C", h: "El coeficiente 5 se cancela con el 1/5." },
  { q: "\\int e^{x/2} \\, dx", a: ["2e^{x/2}+C", "\\frac{1}{2}e^{x/2}+C", "e^{x/2}+C", "2e^x"], c: "2e^{x/2}+C", h: "Dividir por 1/2 es multiplicar por 2." },
  { q: "\\int \\frac{1}{x} \\, dx", a: ["\\ln|x|+C", "e^x", "x^0", "-x^{-2}"], c: "\\ln|x|+C", h: "La integral de 1/x es el logaritmo natural del valor absoluto." },
  { q: "\\int \\frac{4}{x} \\, dx", a: ["4\\ln|x|+C", "\\ln|x^4|+C", "\\frac{4}{x^2}", "4x"], c: "4\\ln|x|+C", h: "Saca la constante 4 de la integral." },
  { q: "\\int \\frac{1}{x+1} \\, dx", a: ["\\ln|x+1|+C", "\\ln x + 1", "\\frac{1}{(x+1)^2}", "x+1"], c: "\\ln|x+1|+C", h: "u = x+1, du = dx. Es una forma du/u." },
  { q: "\\int \\frac{1}{2x-3} \\, dx", a: ["\\frac{1}{2}\\ln|2x-3|+C", "2\\ln|2x-3|+C", "\\ln|2x-3|+C", "\\frac{1}{2x}"], c: "\\frac{1}{2}\\ln|2x-3|+C", h: "No olvides el 1/2 que sale de la derivada de 2x-3." },
  { q: "\\int 2^x \\, dx", a: ["\\frac{2^x}{\\ln 2}+C", "2^x\\ln 2+C", "2^{x+1}", "\\frac{2^{x+1}}{x+1}"], c: "\\frac{2^x}{\\ln 2}+C", h: "Integral de a^x es a^x/ln(a)." },
  { q: "\\int 10^x \\, dx", a: ["\\frac{10^x}{\\ln 10}+C", "10^x\\ln 10+C", "x^{10}", "10x"], c: "\\frac{10^x}{\\ln 10}+C", h: "Usa la fórmula para bases distintas a 'e'." },
  { q: "\\int (e^x + 1) \\, dx", a: ["e^x+x+C", "e^x+C", "xe^x+x", "e^{x+1}"], c: "e^x+x+C", h: "Integra e^x y luego integra la constante 1." },
  { q: "\\int e^x \\sin(e^x) \\, dx", a: ["-\\cos(e^x)+C", "\\cos(e^x)+C", "e^x\\cos(e^x)", "\\sin(e^x)"], c: "-\\cos(e^x)+C", h: "Sustitución u = e^x." },
  { q: "\\int \\frac{e^x}{e^x+5} \\, dx", a: ["\\ln(e^x+5)+C", "e^x+5", "\\ln(e^x)", "\\frac{1}{e^x+5}"], c: "\\ln(e^x+5)+C", h: "El numerador es la derivada del denominador." },
  { q: "\\int \\frac{\\ln x}{x} \\, dx", a: ["\\frac{(\\ln x)^2}{2}+C", "\\ln(\\ln x)+C", "\\frac{1}{x^2}", "\\ln x^2"], c: "\\frac{(\\ln x)^2}{2}+C", h: "Sustitución u = ln(x), du = 1/x dx." },
  { q: "\\int \\frac{1}{x\\ln x} \\, dx", a: ["\\ln|\\ln x|+C", "(\\ln x)^2+C", "\\frac{1}{\\ln x}", "\\ln x"], c: "\\ln|\\ln x|+C", h: "Sustitución u = ln(x), du/u da logaritmo de u." },
  { q: "\\int a^x \\, dx", a: ["\\frac{a^x}{\\ln a}+C", "a^x\\ln a+C", "a^{x+1}", "xa^{x-1}"], c: "\\frac{a^x}{\\ln a}+C", h: "Fórmula general para integrales exponenciales de base a." },
  { q: "\\int (e^{2x} + e^{-2x}) \\, dx", a: ["\\frac{1}{2}e^{2x}-\\frac{1}{2}e^{-2x}+C", "e^{2x}-e^{-2x}+C", "\\frac{1}{2}(e^{2x}+e^{-2x})", "2e^{2x}"], c: "\\frac{1}{2}e^{2x}-\\frac{1}{2}e^{-2x}+C", h: "Cada término genera un factor de 1/2 o -1/2." },
  { q: "\\int \\frac{dx}{3x}", a: ["\\frac{1}{3}\\ln|x|+C", "3\\ln|x|+C", "\\ln|3x|+C", "\\frac{1}{3x^2}"], c: "\\frac{1}{3}\\ln|x|+C", h: "Saca el 1/3 de la integral." },
  { q: "\\int e^{x+3} \\, dx", a: ["e^{x+3}+C", "e^x+3+C", "\\frac{e^{x+4}}{4}", "3e^x"], c: "e^{x+3}+C", h: "La derivada del exponente es 1, no cambia nada." },

  // --- 61-80: DEFINIDAS ---
  { q: "\\int_{0}^{1} x \\, dx", a: ["1/2", "1", "2", "0"], c: "1/2", h: "Evaluación: [x²/2] de 0 a 1." },
  { q: "\\int_{1}^{2} x^2 \\, dx", a: ["7/3", "3", "8/3", "1"], c: "7/3", h: "Evaluación: (2³/3) - (1³/3) = 8/3 - 1/3." },
  { q: "\\int_{0}^{3} 2 \\, dx", a: ["6", "3", "0", "2"], c: "6", h: "La integral de 2 es 2x. Evaluada: 2(3) - 2(0)." },
  { q: "\\int_{1}^{e} \\frac{1}{x} \\, dx", a: ["1", "e", "0", "\\ln 2"], c: "1", h: "ln(e) - ln(1) = 1 - 0 = 1." },
  { q: "\\int_{0}^{\\pi/2} \\cos x \\, dx", a: ["1", "0", "\\pi", "-1"], c: "1", h: "sin(π/2) - sin(0) = 1 - 0." },
  { q: "\\int_{0}^{1} (x^2 + 1) \\, dx", a: ["4/3", "1", "2/3", "2"], c: "4/3", h: "(1³/3 + 1) - (0)." },
  { q: "\\int_{0}^{2} 3x^2 \\, dx", a: ["8", "12", "4", "24"], c: "8", h: "Integral es x³. 2³ - 0³ = 8." },
  { q: "\\int_{-1}^{1} x^3 \\, dx", a: ["0", "1/2", "2", "-1"], c: "0", h: "La integral de una función impar en un intervalo simétrico es 0." },
  { q: "\\int_{1}^{4} \\sqrt{x} \\, dx", a: ["14/3", "12/3", "7/3", "2"], c: "14/3", h: "2/3 * (4^{3/2} - 1^{3/2}) = 2/3 * (8 - 1)." },
  { q: "\\int_{0}^{1} e^x \\, dx", a: ["e-1", "e", "1", "0"], c: "e-1", h: "e¹ - e⁰ = e - 1." },
  { q: "\\int_{0}^{1} (1-x) \\, dx", a: ["1/2", "1", "0", "-1/2"], c: "1/2", h: "(1 - 1/2) - (0)." },
  { q: "\\int_{2}^{3} dx", a: ["1", "5", "2", "3"], c: "1", h: "3 - 2 = 1." },
  { q: "\\int_{0}^{\\pi} \\sin x \\, dx", a: ["2", "0", "1", "-2"], c: "2", h: "-cos(π) - (-cos(0)) = 1 + 1 = 2." },
  { q: "\\int_{1}^{2} \\frac{1}{x^2} \\, dx", a: ["1/2", "1", "3/4", "-1/2"], c: "1/2", h: "[-1/x] de 1 a 2: -1/2 - (-1) = 1/2." },
  { q: "\\int_{0}^{1} (4x^3) \\, dx", a: ["1", "4", "0.5", "16"], c: "1", h: "x⁴ evaluado de 0 a 1." },
  { q: "\\int_{-1}^{1} x^2 \\, dx", a: ["2/3", "0", "1/3", "1"], c: "2/3", h: "(1/3) - (-1/3) = 2/3." },
  { q: "\\int_{0}^{2} (x+1) \\, dx", a: ["4", "2", "6", "3"], c: "4", h: "x²/2 + x evaluado en 2: (2+2) - 0 = 4." },
  { q: "\\int_{1}^{e^2} \\frac{1}{x} \\, dx", a: ["2", "e", "1", "0"], c: "2", h: "ln(e²) - ln(1) = 2 - 0 = 2." },
  { q: "\\int_{0}^{\\pi/4} \\sec^2 x \\, dx", a: ["1", "0", "\\sqrt{2}", "1/2"], c: "1", h: "tan(π/4) - tan(0) = 1 - 0 = 1." },
  { q: "\\int_{0}^{1} 10x^4 \\, dx", a: ["2", "10", "1", "5"], c: "2", h: "2x⁵ evaluado de 0 a 1." },

  // --- 81-105: SUSTITUCIÓN Y ESPECIALES ---
  { q: "\\int \\frac{2x}{x^2+1} \\, dx", a: ["\\ln(x^2+1)+C", "2\\ln(x^2+1)", "\\arctan x", "x^2+1"], c: "\\ln(x^2+1)+C", h: "Sustitución u = x²+1, du = 2x dx." },
  { q: "\\int x e^{x^2} \\, dx", a: ["\\frac{1}{2}e^{x^2}+C", "e^{x^2}+C", "x^2e^{x^2}", "2e^{x^2}"], c: "\\frac{1}{2}e^{x^2}+C", h: "u = x², du = 2x dx. Falta un factor 1/2." },
  { q: "\\int \\sin^2 x \\cos x \\, dx", a: ["\\frac{\\sin^3 x}{3}+C", "\\frac{\\cos^3 x}{3}+C", "\\sin^3 x", "\\cos^2 x"], c: "\\frac{\\sin^3 x}{3}+C", h: "u = sin(x), du = cos(x) dx." },
  { q: "\\int \\frac{\\cos x}{\\sin x} \\, dx", a: ["\\ln|\\sin x|+C", "\\ln|\\cos x|+C", "\\tan x", "-\\ln|\sin x|"], c: "\\ln|\\sin x|+C", h: "u = sin(x), du = cos(x) dx. Es la cotangente." },
  { q: "\\int (x+1)^5 \\, dx", a: ["\\frac{(x+1)^6}{6}+C", "x^6+x", "(x+1)^6", "6(x+1)^4"], c: "\\frac{(x+1)^6}{6}+C", h: "u = x+1, du = dx. Regla de la potencia." },
  { q: "\\int \\frac{e^{\\sqrt{x}}}{\\sqrt{x}} \\, dx", a: ["2e^{\\sqrt{x}}+C", "e^{\\sqrt{x}}+C", "\\frac{1}{2}e^{\\sqrt{x}}", "2\\sqrt{x}"], c: "2e^{\\sqrt{x}}+C", h: "u = √x, du = 1/(2√x) dx." },
  { q: "\\int \\frac{dx}{x^2+1}", a: ["\\arctan x + C", "\\ln|x^2+1|", "\\arcsin x", "-\\frac{1}{x}"], c: "\\arctan x + C", h: "Integral inmediata que resulta en arcotangente." },
  { q: "\\int \\frac{dx}{\\sqrt{1-x^2}}", a: ["\\arcsin x + C", "\\arccos x", "\\arctan x", "\\ln|x|"], c: "\\arcsin x + C", h: "Integral inmediata que resulta en arcoseno." },
  { q: "\\int x(x^2+5)^{10} \\, dx", a: ["\\frac{(x^2+5)^{11}}{22}+C", "\\frac{(x^2+5)^{11}}{11}", "x^2+5", "10x"], c: "\\frac{(x^2+5)^{11}}{22}+C", h: "u = x²+5, du = 2x dx." },
  { q: "\\int \\cos^4 x \\sin x \\, dx", a: ["-\\frac{\\cos^5 x}{5}+C", "\\frac{\\cos^5 x}{5}+C", "\\frac{\\sin^5 x}{5}", "-\\sin^5 x"], c: "-\\frac{\\cos^5 x}{5}+C", h: "u = cos(x), du = -sin(x) dx." },
  { q: "\\int \\frac{x}{x^2+9} \\, dx", a: ["\\frac{1}{2}\\ln(x^2+9)+C", "\\ln(x^2+9)", "\\frac{1}{3}\\arctan(x/3)", "x/2"], c: "\\frac{1}{2}\\ln(x^2+9)+C", h: "Derivada del denominador es 2x." },
  { q: "\\int e^{\\cos x} \\sin x \\, dx", a: ["-e^{\\cos x}+C", "e^{\\cos x}+C", "e^{\\sin x}", "\\sin(e^x)"], c: "-e^{\\cos x}+C", h: "u = cos(x), du = -sin(x) dx." },
  { q: "\\int \\frac{\\sec^2 x}{\\tan x} \\, dx", a: ["\\ln|\\tan x|+C", "\\tan^2 x", "\\sec x", "\\ln|\\cos x|"], c: "\\ln|\\tan x|+C", h: "u = tan(x), du = sec²(x) dx." },
  { q: "\\int \\frac{1}{x(\\ln x)^2} \\, dx", a: ["-\\frac{1}{\\ln x}+C", "\\ln(\\ln x)", "(\\ln x)^{-2}", "1/x"], c: "-\\frac{1}{\\ln x}+C", h: "u = ln(x), es la integral de u^{-2}." },
  { q: "\\int x^2 \\sqrt{x^3+1} \\, dx", a: ["\\frac{2}{9}(x^3+1)^{3/2}+C", "\\frac{2}{3}(x^3+1)^{3/2}", "x^3+1", "\\frac{1}{3}(x^3+1)"], c: "\\frac{2}{9}(x^3+1)^{3/2}+C", h: "u = x³+1, du = 3x² dx." },
  { q: "\\int \\frac{dx}{x+10}", a: ["\\ln|x+10|+C", "\\ln x + 10", "1/10", "x+10"], c: "\\ln|x+10|+C", h: "Sustitución lineal simple." },
  { q: "\\int \\sin(x)e^{\\cos x} \\, dx", a: ["-e^{\\cos x}+C", "e^{\\cos x}+C", "e^{\\sin x}", "-\\cos x"], c: "-e^{\\cos x}+C", h: "u = cos(x)." },
  { q: "\\int \\frac{x^2}{x^3-1} \\, dx", a: ["\\frac{1}{3}\\ln|x^3-1|+C", "\\ln|x^3-1|", "3\\ln|x^3-1|", "x^2"], c: "\\frac{1}{3}\\ln|x^3-1|+C", h: "du = 3x² dx." },
  { q: "\\int \\sec^2(5x) \\, dx", a: ["\\frac{1}{5}\\tan(5x)+C", "5\\tan(5x)+C", "\\tan(5x)", "\\sec(5x)"], c: "\\frac{1}{5}\\tan(5x)+C", h: "No olvides el factor 1/5." },
  { q: "\\int (2x+3)^4 \\, dx", a: ["\\frac{(2x+3)^5}{10}+C", "\\frac{(2x+3)^5}{5}", "2(2x+3)^5", "(2x+3)^5"], c: "\\frac{(2x+3)^5}{10}+C", h: "u = 2x+3, du = 2dx." },
  { q: "\\int \\frac{e^x}{1+e^x} \\, dx", a: ["\\ln(1+e^x)+C", "e^x", "1+e^x", "\\ln(e^x)"], c: "\\ln(1+e^x)+C", h: "La derivada de 1+e^x está en el numerador." },
  { q: "\\int \\frac{\\sin x}{1+\\cos x} \\, dx", a: ["-\\ln|1+\\cos x|+C", "\\ln|1+\\cos x|+C", "\\tan x", "\\sin x"], c: "-\\ln|1+\\cos x|+C", h: "u = 1+cos(x), du = -sin(x) dx." },
  { q: "\\int x e^{-x^2} \\, dx", a: ["-\\frac{1}{2}e^{-x^2}+C", "\\frac{1}{2}e^{-x^2}+C", "-e^{-x^2}", "e^{x^2}"], c: "-\\frac{1}{2}e^{-x^2}+C", h: "u = -x², du = -2x dx." },
  { q: "\\int \\frac{dx}{x-5}", a: ["\\ln|x-5|+C", "\\ln 5", "x-5", "1/x"], c: "\\ln|x-5|+C", h: "Integral de la forma du/u." },
  { q: "\\int \\cos(2x-1) \\, dx", a: ["\\frac{1}{2}\\sin(2x-1)+C", "2\\sin(2x-1)+C", "-\\frac{1}{2}\\sin(2x-1)", "\\sin(x)"], c: "\\frac{1}{2}\\sin(2x-1)+C", h: "u = 2x-1, du = 2dx." }
];